apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  labels: 
    app: pvc
spec:
  resources:
    request:
    storage: 5Gi
  acessModes:
  - ReadWriteOnce
  storageClassName: standard
