apiVersion: autoscaling/v2
kind: HorizotalPodAutoscaler
metadata:
  name: mobile-hpa
  labels:
    app: mobile
spec:
  ScaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mobile-deploy
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: CPU
      target: Utilization
      avergeUtilization: 50
    
